import 'package:equatable/equatable.dart';
import 'emotional_state.dart';
import 'goal.dart';
import 'personality.dart';
import 'interaction_preference.dart';
import 'motivation_factor.dart';
import 'behavior_metrics.dart';

/// Represents the dynamic life profile of a user
class Persona extends Equatable {
  /// The unique identifier of the persona
  final String id;
  
  /// The user ID associated with this persona
  final String userId;
  
  /// Basic information about the user (name, age, occupation, etc.)
  final Map<String, dynamic> basicInfo;
  
  /// The personality assessment of the user
  final Personality personality;
  
  /// The history of emotional states of the user
  final List<EmotionalState> emotionalStates;
  
  /// The current emotional state of the user
  final EmotionalState currentEmotionalState;
  
  /// The goals set by the user
  final List<Goal> goals;
  
  /// Metrics about the user's behavior
  final BehaviorMetrics behaviorMetrics;
  
  /// Factors that motivate the user
  final List<MotivationFactor> motivationFactors;
  
  /// The user's preferences for interaction with the AI
  final InteractionPreference interactionPreference;
  
  /// Insights about the user generated by AI
  final List<String> insights;
  
  /// The timestamp when this persona was created
  final DateTime createdAt;
  
  /// The timestamp when this persona was last updated
  final DateTime updatedAt;
  
  /// The version of this persona
  final int version;

  const Persona({
    required this.id,
    required this.userId,
    required this.basicInfo,
    required this.personality,
    required this.emotionalStates,
    required this.currentEmotionalState,
    required this.goals,
    required this.behaviorMetrics,
    required this.motivationFactors,
    required this.interactionPreference,
    required this.insights,
    required this.createdAt,
    required this.updatedAt,
    required this.version,
  });

  @override
  List<Object?> get props => [
    id,
    userId,
    basicInfo,
    personality,
    currentEmotionalState,
    goals,
    behaviorMetrics,
    motivationFactors,
    interactionPreference,
    insights,
    version,
  ];
}
